#!/usr/bin/env bash
# install-opencode.sh — compile the portable orchestrate skill into OpenCode.
#   ./install-opencode.sh [--scope user|project] [--dir <path>]
#   user (default): ~/.config/opencode + ~/.agents/skills
#   project:        ./.opencode        + ./.agents/skills
#
# Skill-native (ADR-0034): OpenCode reads Agent Skills from the cross-tool
# .agents/skills root (same location Codex reads), so the skill installs there
# as ONE copy (SKILL.md + references/ + runtime/); the OpenCode config dir keeps
# only the OpenCode-native surfaces (agents/, plugins/, commands/ — plural, the
# documented current layout). No AGENTS.md concatenation.
#
# All harness mapping logic lives in scripts/harness-lib/ (ADR-0037); this driver
# names the orchestrate paths and prints the operator summary. HARNESS_LIB
# overrides the lib location for tmp copies.
set -euo pipefail

PLUGIN_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SKILL_DIR="$PLUGIN_ROOT/skills/orchestrate"
CMD_DIR="$PLUGIN_ROOT/commands"
AGENTS="$SKILL_DIR/references/agents.yaml"
LIB="${HARNESS_LIB:-$(cd "$PLUGIN_ROOT/../.." && pwd)/scripts/harness-lib}"
. "$LIB/common.sh"; . "$LIB/opencode.sh"
parse_scope_args "$@"

case "$SCOPE" in
  user)    DEST="${OVERRIDE:-${XDG_CONFIG_HOME:-$HOME/.config}/opencode}" ;;
  project) DEST="${OVERRIDE:-$PWD/.opencode}" ;;
  *) echo "scope must be user|project" >&2; exit 64 ;;
esac
require_yq4
resolve_skills_root

SKILL_DEST="$SKILLS_ROOT/orchestrate"; RT_DEST="$SKILL_DEST/runtime"
AGENTS_DEST="$DEST/agents"; PLUGIN_DEST="$DEST/plugins"; CMDS_DEST="$DEST/commands"

mkdir -p "$AGENTS_DEST" "$PLUGIN_DEST" "$CMDS_DEST"
install_skill "$SKILL_DEST" <<BRAINADD

<!-- OpenCode dispatch addendum (generated by install-opencode.sh; ADR-0034) -->
## OpenCode: runtime location and how to dispatch a persona

Runtime helpers live in THIS skill's directory. First Bash action of the session:

    export PATH="$RT_DEST:\$PATH"

so \`ledger.sh\` / \`worktree.sh\` / \`adr.sh\` resolve by bare name (ADR-0018). (The
orchestrate plugin also prepends this via the documented \`shell.env\` hook at
every shell invocation; the export above is the load-time fallback.)

On OpenCode, dispatch personas via the native task tool / \`@<persona>\` mention —
the installed agents/ definitions carry each persona's tool subtraction, and the
orchestrate plugin's \`tool.execute.before\` floor fail-closes scope violations
(a thrown error blocks the call). Confinement here is permission+hook based, not
an OS sandbox: the write-scope/run-scope hooks are the enforcement layer.

Write-ahead (ADR-0011 spirit): OpenCode's documented event list has no
subagent-start hook, so write-ahead is NOT plugin-driven here. Immediately
before dispatching an implementer or actuator, the router runs
\`$RT_DEST/hooks/on-writer-dispatch.sh\` itself (in-loop, deterministic) so
the ledger 'dispatched' entry and lease land on disk before the writer's
first tool call — same guarantee the plugin gives for free on harnesses where
a subagent-start-style event does fire.
BRAINADD

for p in $(personas); do
  oc_agent_md "$p" "$AGENTS_DEST/$p.md"
  echo "  subagent -> $AGENTS_DEST/$p.md   (model: $(oc_model "$(p_tier "$p" model)"))"
done

# Command parity (OpenCode commands support \$ARGUMENTS): compiled from the same
# command sources the Claude Code plugin ships; descriptions parsed, never restated.
for c in init status feedback; do
  oc_command "$CMD_DIR/$c.md" "$CMDS_DEST/orchestrate-$c.md"
  echo "  command  -> $CMDS_DEST/orchestrate-$c.md"
done

# Enforcement plugin: per-agent allow/deny is real subtraction; the plugin enforces
# path/branch scope AND drives the durable ledger by shelling out to the
# single-source runtime. The floor is DERIVED from the contract's watch classes.
oc_plugin_ts "$PLUGIN_DEST/orchestrate.ts" orchestrate "$RT_DEST"
echo "  plugin   -> $PLUGIN_DEST/orchestrate.ts"

cat <<EOF

OpenCode install complete ($SCOPE scope).
  skill     -> $SKILL_DEST/  (SKILL.md + references/ + runtime/; OpenCode reads
               .agents/skills natively — the skill tool loads it on demand; ADR-0034)
  subagents -> $AGENTS_DEST/{...}.md   (tools: + permission: = real subtraction; model from tier)
  commands  -> $CMDS_DEST/orchestrate-{init,status,feedback}.md  (/orchestrate-init etc.)
  plugin    -> $PLUGIN_DEST/orchestrate.ts   (auto-loads; a THROW in tool.execute.before
               blocks the call — documented fail-closed)

Actuator credential confinement is ADVISORY (ADR-0002): scope the actuator lane's
creds to its leased targets in your deployment; serialization (the lease) is the
only guaranteed layer.

Set HELDOUT_ROOT and ASSIGNED_BRANCH in the env OpenCode runs under. No config
file — /orchestrate-init to start or resume; compaction recovers via the plugin's
session.compacted hook. Live-verified on 1.18.4 (tests/integration/test_opencode_*):
plugin loads, the tool.execute.before floor blocks for real, and skills load inside
'opencode run'. STILL UNVERIFIED: permission-key coverage for write, and whether
session.compacted actually fires post-compaction (registration-only bounded).
Ledger: .agents/runs/orchestrate/board.jsonl.
EOF
