#!/usr/bin/env bash
# install-opencode.sh — compile the portable orchestrate skill into OpenCode.
#   ./install-opencode.sh [--scope user|project] [--dir <path>]
#   user (default): ~/.config/opencode + ~/.agents/skills
#   project:        ./.opencode        + ./.agents/skills
#
# Skill-native (ADR-0034): OpenCode reads Agent Skills from the cross-tool
# .agents/skills root (same location Codex reads), so the skill installs there
# as ONE copy (SKILL.md + references/ + runtime/); the OpenCode config dir keeps
# only the OpenCode-native surfaces (agents/, plugins/, commands/ — plural, the
# documented current layout). No AGENTS.md concatenation.
set -euo pipefail

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../skills/orchestrate" && pwd)"
CMD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../commands" && pwd)"
AGENTS="$SKILL_DIR/references/agents.yaml"
SCOPE=user; OVERRIDE=""
while [ $# -gt 0 ]; do case "$1" in
  --scope) SCOPE="${2:?}"; shift 2 ;;
  --dir)   OVERRIDE="${2:?}"; shift 2 ;;
  *) echo "usage: $0 [--scope user|project] [--dir <path>]" >&2; exit 64 ;;
esac; done

case "$SCOPE" in
  user)    DEST="${OVERRIDE:-${XDG_CONFIG_HOME:-$HOME/.config}/opencode}"
           SKILLS_ROOT="${OVERRIDE:+$OVERRIDE/.agents/skills}"; SKILLS_ROOT="${SKILLS_ROOT:-$HOME/.agents/skills}" ;;
  project) DEST="${OVERRIDE:-$PWD/.opencode}"
           SKILLS_ROOT="${OVERRIDE:-$PWD}/.agents/skills" ;;
  *) echo "scope must be user|project" >&2; exit 64 ;;
esac
yq --version 2>/dev/null | grep -qE 'mikefarah|version v?4\.' || { echo "FATAL: yq (v4, mikefarah) required — the Python (kislyuk) yq emits JSON-quoted scalars and will not work." >&2; exit 1; }

SKILL_DEST="$SKILLS_ROOT/orchestrate"; RT_DEST="$SKILL_DEST/runtime"
AGENTS_DEST="$DEST/agents"; PLUGIN_DEST="$DEST/plugins"; CMDS_DEST="$DEST/commands"

# tools: is deprecated in favor of permission:, but still honored — emit BOTH:
# tools: for older builds, permission: (documented keys only: edit/bash/webfetch)
# as the current declarative deny layer. The plugin hook floor sits on top.
oc_tools() { local p="$1" read web write run rd=false gp=false gl=false wf=false wr=false ed=false bash=false
  read="$(yq ".personas.$p.capabilities.read" "$AGENTS")"; web="$(yq ".personas.$p.capabilities.web" "$AGENTS")"
  write="$(yq ".personas.$p.capabilities.write" "$AGENTS")"; run="$(yq ".personas.$p.capabilities.run" "$AGENTS")"
  [ "$read" = true ] && { rd=true; gp=true; gl=true; }; [ "$web" = true ] && wf=true
  case "$write" in full) wr=true; ed=true;; spec-only|results-only) wr=true;; esac   # results-only: scoped Write, no Edit (ADR-0014); write-scope hook confines the path
  case "$run" in full|tests-only) bash=true;; esac
  printf 'tools:\n  read: %s\n  grep: %s\n  glob: %s\n  webfetch: %s\n  write: %s\n  edit: %s\n  bash: %s\n' "$rd" "$gp" "$gl" "$wf" "$wr" "$ed" "$bash"
  printf 'permission:\n  edit: %s\n  bash: %s\n  webfetch: %s\n' \
    "$([ "$ed" = true ] && echo allow || echo deny)" \
    "$([ "$bash" = true ] && echo allow || echo deny)" \
    "$([ "$wf" = true ] && echo allow || echo deny)"; }
body() { awk 'f==2{print} /^---[[:space:]]*$/{f++}' "$1"; }

mkdir -p "$AGENTS_DEST" "$PLUGIN_DEST" "$CMDS_DEST" "$SKILL_DEST" "$RT_DEST"
cp -r "$SKILL_DIR/runtime/." "$RT_DEST/"
cp -r "$SKILL_DIR/references" "$SKILL_DEST/references"
chmod +x "$RT_DEST"/*.sh "$RT_DEST"/hooks/*.sh
# SKILL.md is copied verbatim FIRST (a skill file must OPEN with its YAML
# frontmatter — a prepended banner would break skills discovery), then the
# harness addendum is appended (generated distribution, ADR-0007/0034).
cat "$SKILL_DIR/SKILL.md" > "$SKILL_DEST/SKILL.md"
cat >> "$SKILL_DEST/SKILL.md" <<BRAINADD

<!-- OpenCode dispatch addendum (generated by install-opencode.sh; ADR-0034) -->
## OpenCode: runtime location and how to dispatch a persona

Runtime helpers live in THIS skill's directory. First Bash action of the session:

    export PATH="$RT_DEST:\$PATH"

so \`ledger.sh\` / \`worktree.sh\` / \`adr.sh\` resolve by bare name (ADR-0018). (The
orchestrate plugin also prepends this at load; the export is the fallback.)

On OpenCode, dispatch personas via the native task tool / \`@<persona>\` mention —
the installed agents/ definitions carry each persona's tool subtraction, and the
orchestrate plugin's \`tool.execute.before\` floor fail-closes scope violations
(a thrown error blocks the call). Confinement here is permission+hook based, not
an OS sandbox: the write-scope/run-scope hooks are the enforcement layer.
BRAINADD

for p in $(yq '.personas | keys | .[]' "$AGENTS"); do
  desc="$(yq ".personas.$p.description" "$AGENTS")"; bsrc="$SKILL_DIR/references/$(yq ".personas.$p.body" "$AGENTS")"
  { printf -- '---\ndescription: %s\nmode: subagent\n' "$desc"; oc_tools "$p"; printf -- '---\n\n'; body "$bsrc"; } > "$AGENTS_DEST/$p.md"
  echo "  subagent -> $AGENTS_DEST/$p.md"
done

# Command parity (OpenCode commands support \$ARGUMENTS): /orchestrate-init,
# /orchestrate-status, /orchestrate-feedback from the same command sources the
# Claude Code plugin ships. Frontmatter is rewritten (OpenCode keys only).
oc_command() { # <src.md> <dest.md> <description>
  { printf -- '---\ndescription: %s\n---\n' "$3"; body "$1"; } > "$2"
  echo "  command  -> $2"
}
oc_command "$CMD_DIR/init.md"     "$CMDS_DEST/orchestrate-init.md"     "Standing operator loop — goal in, resume with no args. Flags: --models=dynamic|quick|inherit"
oc_command "$CMD_DIR/status.md"   "$CMDS_DEST/orchestrate-status.md"   "Operator status update from durable disk state"
oc_command "$CMD_DIR/feedback.md" "$CMDS_DEST/orchestrate-feedback.md" "Capture run feedback durably (review sidecar + version-stamped row)"

# Plugin: per-agent allow/deny is real subtraction; the plugin enforces path/branch
# scope AND drives the durable ledger by shelling out to the single-source runtime.
# A THROWN error in tool.execute.before blocks the call (documented fail-closed).
cat > "$PLUGIN_DEST/orchestrate.ts" <<TS
// orchestrate.ts — calls the shared runtime so policy stays single-source.
import { execFileSync } from "node:child_process";
const RT = "$RT_DEST";
// Runtime helpers (ledger.sh/adr.sh/worktree.sh) resolve by bare name in persona/router
// Bash; the plugin loads once at session start, so prepend the runtime dir to PATH here
// (ADR-0018). Confirm env propagates to the bash tool in your OpenCode version.
process.env.PATH = \`\${RT}:\${process.env.PATH ?? ""}\`;
// env: process.env is NOT cosmetic -- live-probed against 1.18.4 (opencode-live-tier):
// execFileSync's default (no explicit \`env\`) did NOT inherit the live process.env in
// this Bun-compiled build, so every process.env.RESOLVED_PATH/TOOL_INPUT/PATH mutation
// above was invisible to the hook subprocess and EVERY hook silently failed open (a
// read of \$HELDOUT_ROOT leaked with no error). Passing env explicitly is load-bearing.
const sh = (p: string) => { try { execFileSync("bash", [p], { stdio: "inherit", env: process.env }); } catch (e) { throw e; } };
export const orchestrate = async () => ({
  // NOTE (live-probed against 1.18.4, opencode-live-tier): the Hooks type is
  // (input: {tool,sessionID,callID}, output: {args}) => Promise<void> -- args
  // live on the SECOND (output) parameter, not input. A single-arg callback
  // reading input.args always saw undefined, so RESOLVED_PATH/TOOL_INPUT were
  // always "" and every path/command-based hook below silently failed OPEN.
  // Confirmed live: tool.execute.before fired with
  //   input={tool:"read",...} output={args:{filePath:"..."}}
  // for the read tool, and output={args:{command:"...",workdir:"..."}} for bash.
  "tool.execute.before": async (input: any, output: any) => {
    const tool = input?.tool ?? "";
    const args = output?.args ?? input?.args ?? {};
    process.env.RESOLVED_PATH = String(args?.path ?? args?.filePath ?? "");
    process.env.TOOL_INPUT = String(args?.command ?? args?.patchText ?? "");
    if (["read","grep","glob"].includes(tool)) sh(\`\${RT}/hooks/deny-heldout-read.sh\`);
    if (tool === "bash") { sh(\`\${RT}/hooks/keep-on-branch.sh\`); sh(\`\${RT}/hooks/gate-prod-apply.sh\`); sh(\`\${RT}/hooks/run-scope.sh\`); }  // gate is the hard floor; run-scope confines verifier Bash
    // write/edit: legacy tool names some providers still expose. apply_patch: the
    // ACTUAL write tool observed live for OpenAI models on this build (its args
    // carry patchText, not a single path) -- route it too so an unresolved path
    // fails CLOSED (write-scope's fail-closed default) instead of bypassing
    // confinement entirely. Full multi-path apply_patch parsing on OpenCode is a
    // separate gap (write-scope.sh's apply_patch parser only reads stdin JSON,
    // which OpenCode's hook invocation never sends) -- see probe-results.md.
    if (tool === "write" || tool === "edit" || tool === "apply_patch") sh(\`\${RT}/hooks/write-scope.sh\`);  // planner spec/ADR + researcher findings_quarantine + verifier verdicts confinement (self-guards, ADR-0014)
  },
  // Write-ahead for the writer (deterministic): runs before an implementer subagent.
  // The script self-guards on persona=implementer. Event name UNVERIFIED for current
  // OpenCode; if subagent-start isn't exposed, the orchestrator does this in-loop.
  "subagent.start": async () => sh(\`\${RT}/hooks/on-writer-dispatch.sh\`),
  // Automatic compaction recovery: reground + inject authoritative board; halt if
  // ambiguous. session.compacted is the DOCUMENTED post-compaction event.
  "session.compacted": async () => sh(\`\${RT}/hooks/on-compaction.sh\`),
});
TS
echo "  plugin   -> $PLUGIN_DEST/orchestrate.ts"

cat <<EOF

OpenCode install complete ($SCOPE scope).
  skill     -> $SKILL_DEST/  (SKILL.md + references/ + runtime/; OpenCode reads
               .agents/skills natively — the skill tool loads it on demand; ADR-0034)
  subagents -> $AGENTS_DEST/{...}.md   (tools: + permission: = real subtraction)
  commands  -> $CMDS_DEST/orchestrate-{init,status,feedback}.md  (/orchestrate-init etc.)
  plugin    -> $PLUGIN_DEST/orchestrate.ts   (auto-loads; a THROW in tool.execute.before
               blocks the call — documented fail-closed)

Actuator credential confinement is ADVISORY (ADR-0002): scope the actuator lane's
creds to its leased targets in your deployment; serialization (the lease) is the
only guaranteed layer.

Set HELDOUT_ROOT and ASSIGNED_BRANCH in the env OpenCode runs under. No config
file — /orchestrate-init to start or resume; compaction recovers via the plugin's
session.compacted hook. UNVERIFIED against a live install: the subagent.start
event name, permission-key coverage for write, and skills loading inside
'opencode run' — probe once and report drift. Ledger: .agents/runs/orchestrate/board.jsonl.
EOF
