#!/usr/bin/env bash
# install-codex.sh — compile the portable orchestrate skill into Codex CLI.
#   ./install-codex.sh [--scope user|project] [--dir <path>]
#   user (default): ~/.codex (or $CODEX_HOME)    project: ./.codex
#
# All harness mapping + trust machinery lives in scripts/harness-lib/ (ADR-0037);
# this driver names the orchestrate paths, emits the persona TOMLs, and prints
# the operator summary. HARNESS_LIB overrides the lib location for tmp copies.
set -euo pipefail

PLUGIN_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SKILL_DIR="$PLUGIN_ROOT/skills/orchestrate"
AGENTS="$SKILL_DIR/references/agents.yaml"
LIB="${HARNESS_LIB:-$(cd "$PLUGIN_ROOT/../.." && pwd)/scripts/harness-lib}"
. "$LIB/common.sh"; . "$LIB/codex.sh"
# Web is BUILT IN to codex (native Responses `web_search`, on by default).
# ORCHESTRATE_WEB_MCP is an ESCAPE HATCH only: set it to wire a custom web/doc MCP
# server name into the researcher role instead of using the built-in tool.
WEB_MCP="${ORCHESTRATE_WEB_MCP:-}"
parse_scope_args "$@"

case "$SCOPE" in
  user)    DEST="${OVERRIDE:-${CODEX_HOME:-$HOME/.codex}}" ;;
  project) DEST="${OVERRIDE:-$PWD/.codex}" ;;
  *) echo "scope must be user|project" >&2; exit 64 ;;
esac
require_yq4

# Skill-native install (ADR-0034): codex reads Agent Skills from .agents/skills
# (repo) / ~/.agents/skills (user) — SKILL.md + references/ + runtime/ land there
# as ONE copy; $CODEX_HOME keeps only the codex-native surfaces (agent TOMLs,
# hooks.json, config.toml). No AGENTS.md concatenation.
resolve_skills_root
SKILL_DEST="$SKILLS_ROOT/orchestrate"
AGENTS_DEST="$DEST/agents"; RT_DEST="$SKILL_DEST/runtime"; HOOKS="$RT_DEST/hooks"

mkdir -p "$AGENTS_DEST"
# Codex dispatch addendum (ADR-0017). SKILL.md is harness-neutral and says nothing about
# HOW to dispatch; on Codex the mechanism is this launcher, not spawn_agent, so persona
# writes are OS-confined to their lane. Appended only to the generated Codex skill copy.
install_skill "$SKILL_DEST" <<BRAINADD

<!-- Codex dispatch addendum (generated by install-codex.sh; ADR-0017/0034) -->
## Codex: runtime location and how to dispatch a persona

Runtime helpers live in THIS skill's directory. First Bash action of the session:

    export PATH="$RT_DEST:\$PATH"

so \`ledger.sh\` / \`worktree.sh\` / \`adr.sh\` resolve by bare name (ADR-0018).

On Codex, dispatch EVERY persona by running the launcher with the task on stdin, NOT via
\`spawn_agent\`:

    printf '%s' "<the persona's task>" | \\
      dispatch-persona.sh <persona> <ticket_dir> [<repo_root>]

The launcher runs the persona as its own top-level \`codex exec\` whose cwd is the persona's
result lane, so the OS sandbox confines its writes to that lane (source / prod / other-lane
writes are refused at the syscall, even for any sub-spawn) and the per-persona hook floor
also fires. \`spawn_agent\` does NOT confine a persona (all spawned agents share the session
sandbox), so it is not used for dispatch here. Read each persona's result from its scoped
disk path as usual (the disk-first read lane). Lanes: researcher/verifier/planner are
read-only personas confined to their result subtree; the implementer writes at the repo
root; the actuator runs read-only. (This requires the router session's
\`network_access = true\`, set by the installer, so the nested persona \`codex exec\` can reach
the model.)
BRAINADD

mkdir -p "$RT_DEST/personas"
for p in $(personas); do
  desc="$(p_desc "$p")"; sandbox="$(codex_sandbox "$p")"
  web="$(p_cap "$p" web)"; bsrc="$(p_body "$p")"
  model="$(codex_model "$(p_tier "$p" model)")"
  effort="$(codex_effort "$(p_tier "$p" effort)")"
  {
    printf 'name = "%s"\n' "$p"
    printf 'description = "%s"\n' "${desc//\"/\\\"}"
    printf 'sandbox_mode = "%s"\n' "$sandbox"
    [ -n "$model" ]  && printf 'model = "%s"\n' "$model"                       # tier -> model id
    [ -n "$effort" ] && printf 'model_reasoning_effort = "%s"\n' "$effort"     # tier -> reasoning effort (low|medium|high|xhigh)
    # Persona body goes in developer_instructions (NOT `instructions`). Emit ALL
    # root-level keys (incl. this one) BEFORE any [table] header below, or the table
    # would capture them.
    printf 'developer_instructions = """\n'; body "$bsrc"; printf '"""\n'
    # Web: the built-in `web_search` tool is on by default (enabled at config level,
    # not per-role — see config block below). ORCHESTRATE_WEB_MCP escape hatch: if set,
    # wire that MCP server name for the researcher instead. (mcp_servers is a MAP table,
    # [mcp_servers.<name>].) Table header LAST.
    if [ "$web" = true ] && [ -n "$WEB_MCP" ]; then
      printf '[mcp_servers.%s]\n# command/args for your web/doc MCP go here (escape hatch; built-in web_search is the default).\n' "$WEB_MCP"
    fi
  } > "$AGENTS_DEST/$p.toml"
  # Persona body as plain text for the ADR-0017 launcher (dispatch-persona.sh injects it
  # as the persona's standing instructions when running the persona as its own codex exec).
  body "$bsrc" > "$RT_DEST/personas/$p.md"
  echo "  subagent -> $AGENTS_DEST/$p.toml   (sandbox: $sandbox, model: ${model:-default}, effort: ${effort:-default}, web: $web)"
done

# ─────────────────────────────────────────────────────────────────────────────
# Hook wiring + trust seeding (harness-lib/codex.sh).
#
# The PreToolUse floor is DERIVED from the contract (hooks watching a tool-shaped
# class, contract wire order; matcher includes apply_patch — the Codex top-level
# write tool). A wired Codex hook SILENTLY NO-OPS — fails OPEN — unless its sha256
# is trusted in [hooks.state], so the lib (a) writes the managed hooks.json and
# (b) SEEDS [hooks.state] from codex's own hash oracle, then SELF-VERIFIES with a
# live deny probe — never leaving the operator believing the floor is live when it
# is not.
HOOKS_JSON="$DEST/hooks.json"
CONFIG_TOML="$DEST/config.toml"
codex_derive_wiring
ensure_network_access "$CONFIG_TOML"   # ADR-0017: let the router launch confined persona sessions
codex_seed_hook_trust

cat <<EOF

Codex install complete ($SCOPE scope).
  subagents -> $AGENTS_DEST/{...}.toml
  skill     -> $SKILL_DEST/  (SKILL.md + references/ + runtime/; codex auto-discovers
               .agents/skills — invoke \$orchestrate or let the description trigger; ADR-0034)
  hooks     -> $HOOKS_JSON  (wired; matcher includes apply_patch)
  trust     -> $CONFIG_TOML  ([features] hooks=true + [hooks.state] seeds)
  dispatch  -> personas run via $RT_DEST/dispatch-persona.sh (codex exec --cd <lane>); NOT spawn_agent (ADR-0017)
  network   -> $CONFIG_TOML  ([sandbox_workspace_write] network_access=true) so the router can launch confined persona sessions; matches Claude Code's network-open posture, persona WRITES stay OS-confined

Hook wiring + trust were applied automatically (status: $SEED_STATUS). The
reference config below documents the SAME wiring the installer wrote to
$HOOKS_JSON — GENERATED from the same wire list, so it cannot restate a stale
floor (you do NOT need to paste it unless you prefer config-inline hooks):

  # Hooks must be turned ON as a feature, or every [[hooks.*]] table below is inert.
  [features]
  hooks = true
  # Web search is BUILT IN and ON by default; nothing to wire. Uncomment ONLY to
  # override the default mode (live|indexed|cached|disabled):
  #   web_search = "live"   # top-level, or under a [profiles.<name>]; per-role web_search is ignored.

  # NOTE on event names: the config TABLE names are PascalCase here
  # ([[hooks.PreToolUse]], SubagentStart, PostCompact) and the wire
  # \`hook_event_name\` codex emits to the hook is also PascalCase.

$(codex_print_pretooluse_toml)

  # Write-ahead for both writers (deterministic ledger + lease; the gate's ledger half lives inside it):
  [[hooks.SubagentStart]]
  matcher = "implementer|actuator"
  [[hooks.SubagentStart.hooks]]
  type = "command"
  command = "$HOOKS/on-writer-dispatch.sh"

  # Automatic compaction recovery (hands-off):
  [[hooks.PostCompact]]
  [[hooks.PostCompact.hooks]]
  type = "command"
  command = "$HOOKS/on-compaction.sh"

>>> HOOK TRUST (fail-OPEN risk — status: $SEED_STATUS) <<<
A wired Codex hook SILENTLY NO-OPS — fails OPEN — unless its sha256 is trusted in
[hooks.state] (or the run passes --dangerously-bypass-hook-trust). These hooks are the
fail-closed floor (held-out reads, branch guard, prod-apply gate, done-gate); a silent
no-op disarms them. This installer SEEDS [hooks.state] automatically, using the hash
codex itself computes (\`codex app-server\` -> hooks/list -> currentHash; never a guess),
then SELF-VERIFIES that a wired hook actually fires with NO bypass. Outcome:
$(case "$SEED_STATUS" in
seeded) printf '%s' \
"  SEEDED + SELF-VERIFIED. The floor is LIVE on first run — no manual step. A deny
  probe blocked under \`codex exec\` with no bypass, proving the seeded trust takes.";;
seeded-unverified) printf '%s' \
"  SEEDED, NOT self-verified (could not run the live probe this install — e.g. no
  network/auth for a \`codex exec\` round-trip). The seeds use the codex-computed hash,
  but confirm once: run codex in the TUI and ensure no 'Hooks need review' prompt
  appears, OR re-run this installer where a live probe can complete.";;
verify-failed) printf '%s' \
"  *** SEEDING DID NOT TAKE — FLOOR IS NOT LIVE. *** The self-verify deny probe did NOT
  fire under \`codex exec\` even after seeding (likely a codex version/format DRIFT in
  the [hooks.state] key or hash recipe). The seeds were STRIPPED to avoid a false sense
  of safety. Until fixed, make the floor fire MANUALLY:
    1. Interactive: run codex once in the TUI and APPROVE the hooks when prompted.
    2. Headless/CI: \`codex exec --dangerously-bypass-hook-trust [PROMPT]\` (vetted only).
  Please report the drift: the key format or currentHash recipe changed.";;
docs-only) printf '%s' \
"  NOT seeded (codex/auth/python3 unavailable at install time, so the hash oracle and
  self-verify could not run). The floor is NOT live until you establish trust:
    1. Interactive: run codex once in the TUI and APPROVE the hooks when prompted.
    2. Headless/CI: \`codex exec --dangerously-bypass-hook-trust [PROMPT]\` (vetted only).
  Re-run this installer with codex logged in to seed + self-verify automatically.";;
*) printf '%s' "  (unknown seeding status)";;
esac)

Actuator credential confinement is ADVISORY (ADR-0002): scope the actuator lane's
creds to its leased targets in your deployment; serialization (the lease) is the
only guaranteed layer — the skill cannot enforce "no creds for an unleased target".

No config file. Web is built in (web_search, on by default); set ORCHESTRATE_WEB_MCP
ONLY to wire a custom web/doc MCP as an escape hatch. Set HELDOUT_ROOT, then run
/orchestrate to start or resume. Compaction recovers automatically via PostCompact.
Codex spawns subagents only on explicit request; agents.max_depth defaults to 1.
Ledger: .agents/runs/orchestrate/board.jsonl.
EOF
