#!/usr/bin/env bash
# install-codex.sh — compile the portable orchestrate skill into Codex CLI.
#   ./install-codex.sh [--scope user|project] [--dir <path>]
#   user (default): ~/.codex (or $CODEX_HOME)    project: ./.codex
set -euo pipefail

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../skills/orchestrate" && pwd)"
AGENTS="$SKILL_DIR/references/agents.yaml"
# Web is BUILT IN to codex 0.142.1 (native Responses `web_search`, on by default).
# ORCHESTRATE_WEB_MCP is an ESCAPE HATCH only: set it to wire a custom web/doc MCP
# server name into the researcher role instead of using the built-in tool.
WEB_MCP="${ORCHESTRATE_WEB_MCP:-}"
SCOPE=user; OVERRIDE=""
while [ $# -gt 0 ]; do case "$1" in
  --scope) SCOPE="${2:?}"; shift 2 ;;
  --dir)   OVERRIDE="${2:?}"; shift 2 ;;
  *) echo "usage: $0 [--scope user|project] [--dir <path>]" >&2; exit 64 ;;
esac; done

case "$SCOPE" in
  user)    DEST="${OVERRIDE:-${CODEX_HOME:-$HOME/.codex}}"; BRAIN_DIR="$DEST" ;;
  project) DEST="${OVERRIDE:-$PWD/.codex}"; BRAIN_DIR="${OVERRIDE:-$PWD}" ;;   # honor --dir (don't pollute repo root on smoke installs)
  *) echo "scope must be user|project" >&2; exit 64 ;;
esac
yq --version 2>/dev/null | grep -qE 'mikefarah|version v?4\.' || { echo "FATAL: yq (v4, mikefarah) required — the Python (kislyuk) yq emits JSON-quoted scalars and will not work." >&2; exit 1; }

# Skill-native install (ADR-0034): codex reads Agent Skills from .agents/skills
# (repo) / ~/.agents/skills (user) — SKILL.md + references/ + runtime/ land there
# as ONE copy; $CODEX_HOME keeps only the codex-native surfaces (agent TOMLs,
# hooks.json, config.toml). No AGENTS.md concatenation.
case "$SCOPE" in
  user)    SKILLS_ROOT="${OVERRIDE:+$OVERRIDE/.agents/skills}"; SKILLS_ROOT="${SKILLS_ROOT:-$HOME/.agents/skills}" ;;
  project) SKILLS_ROOT="$BRAIN_DIR/.agents/skills" ;;
esac
SKILL_DEST="$SKILLS_ROOT/orchestrate"
AGENTS_DEST="$DEST/agents"; RT_DEST="$SKILL_DEST/runtime"; HOOKS="$RT_DEST/hooks"

codex_sandbox() { local p="$1" w r; w="$(yq ".personas.$p.capabilities.write" "$AGENTS")"; r="$(yq ".personas.$p.capabilities.run" "$AGENTS")"
  if [ "$w" = none ] && [ "$r" = none ]; then echo read-only; else echo workspace-write; fi; }
# agents.yaml tier -> codex 0.142.1 model id.  economy->mini, standard->5.4, premium->frontier.
codex_model() { case "$1" in
  economy)  echo gpt-5.4-mini ;;
  standard) echo gpt-5.4 ;;
  premium)  echo gpt-5.5 ;;
  *)        echo "" ;;   # unknown/empty tier -> omit model line (inherit session default)
esac; }
# agents.yaml effort -> codex model_reasoning_effort enum (low|medium|high|xhigh ONLY).
# `max` is NOT a valid codex value (API rejects it) -> map to the real ceiling, xhigh.
codex_effort() { case "$1" in
  low|medium|high|xhigh) echo "$1" ;;
  max)                   echo xhigh ;;
  *)                     echo "" ;;   # unknown/empty -> omit (inherit)
esac; }
body() { awk 'f==2{print} /^---[[:space:]]*$/{f++}' "$1"; }

mkdir -p "$AGENTS_DEST" "$SKILL_DEST" "$RT_DEST/personas"
cp -r "$SKILL_DIR/runtime/." "$RT_DEST/"
cp -r "$SKILL_DIR/references" "$SKILL_DEST/references"
chmod +x "$RT_DEST"/*.sh "$RT_DEST"/hooks/*.sh
# SKILL.md is copied verbatim FIRST (a skill file must OPEN with its YAML
# frontmatter — a prepended banner would break skills discovery), then the
# harness addendum is appended (generated distribution, ADR-0007/0034).
cat "$SKILL_DIR/SKILL.md" > "$SKILL_DEST/SKILL.md"
# Codex dispatch addendum (ADR-0017). SKILL.md is harness-neutral and says nothing about
# HOW to dispatch; on Codex the mechanism is this launcher, not spawn_agent, so persona
# writes are OS-confined to their lane. Appended only to the generated Codex skill copy.
cat >> "$SKILL_DEST/SKILL.md" <<BRAINADD

<!-- Codex dispatch addendum (generated by install-codex.sh; ADR-0017/0034) -->
## Codex: runtime location and how to dispatch a persona

Runtime helpers live in THIS skill's directory. First Bash action of the session:

    export PATH="$RT_DEST:\$PATH"

so \`ledger.sh\` / \`worktree.sh\` / \`adr.sh\` resolve by bare name (ADR-0018).

On Codex, dispatch EVERY persona by running the launcher with the task on stdin, NOT via
\`spawn_agent\`:

    printf '%s' "<the persona's task>" | \\
      dispatch-persona.sh <persona> <ticket_dir> [<repo_root>]

The launcher runs the persona as its own top-level \`codex exec\` whose cwd is the persona's
result lane, so the OS sandbox confines its writes to that lane (source / prod / other-lane
writes are refused at the syscall, even for any sub-spawn) and the per-persona hook floor
also fires. \`spawn_agent\` does NOT confine a persona (all spawned agents share the session
sandbox), so it is not used for dispatch here. Read each persona's result from its scoped
disk path as usual (the disk-first read lane). Lanes: researcher/verifier/planner are
read-only personas confined to their result subtree; the implementer writes at the repo
root; the actuator runs read-only. (This requires the router session's
\`network_access = true\`, set by the installer, so the nested persona \`codex exec\` can reach
the model.)
BRAINADD

for p in $(yq '.personas | keys | .[]' "$AGENTS"); do
  desc="$(yq ".personas.$p.description" "$AGENTS")"; sandbox="$(codex_sandbox "$p")"
  web="$(yq ".personas.$p.capabilities.web" "$AGENTS")"; bsrc="$SKILL_DIR/references/$(yq ".personas.$p.body" "$AGENTS")"
  model="$(codex_model "$(yq ".personas.$p.tier.model" "$AGENTS")")"
  effort="$(codex_effort "$(yq ".personas.$p.tier.effort" "$AGENTS")")"
  {
    printf 'name = "%s"\n' "$p"
    printf 'description = "%s"\n' "${desc//\"/\\\"}"
    printf 'sandbox_mode = "%s"\n' "$sandbox"
    [ -n "$model" ]  && printf 'model = "%s"\n' "$model"                       # tier -> model id
    [ -n "$effort" ] && printf 'model_reasoning_effort = "%s"\n' "$effort"     # tier -> reasoning effort (low|medium|high|xhigh)
    # Persona body goes in developer_instructions (NOT `instructions`). Emit ALL
    # root-level keys (incl. this one) BEFORE any [table] header below, or the table
    # would capture them.
    printf 'developer_instructions = """\n'; body "$bsrc"; printf '"""\n'
    # Web: the built-in `web_search` tool is on by default (enabled at config level,
    # not per-role — see config block below). ORCHESTRATE_WEB_MCP escape hatch: if set,
    # wire that MCP server name for the researcher instead. (mcp_servers is a MAP table,
    # [mcp_servers.<name>], so the OLD `mcp_servers = ["web"]` sequence is GONE — it tripped
    # --strict-config with "invalid type: sequence, expected a map".) Table header LAST.
    if [ "$web" = true ] && [ -n "$WEB_MCP" ]; then
      printf '[mcp_servers.%s]\n# command/args for your web/doc MCP go here (escape hatch; built-in web_search is the default).\n' "$WEB_MCP"
    fi
  } > "$AGENTS_DEST/$p.toml"
  # Persona body as plain text for the ADR-0017 launcher (dispatch-persona.sh injects it
  # as the persona's standing instructions when running the persona as its own codex exec).
  body "$bsrc" > "$RT_DEST/personas/$p.md"
  echo "  subagent -> $AGENTS_DEST/$p.toml   (sandbox: $sandbox, model: ${model:-default}, effort: ${effort:-default}, web: $web)"
done

# ─────────────────────────────────────────────────────────────────────────────
# Hook wiring + trust seeding (codex-cli 0.142.x).
#
# Codex's PreToolUse matcher must include `apply_patch` (top-level writes surface
# as that tool, NOT Edit/Write). And a wired Codex hook SILENTLY NO-OPS — fails
# OPEN — unless its sha256 is trusted in [hooks.state] (or the run passes
# --dangerously-bypass-hook-trust). So we (a) WRITE a managed hooks.json wiring the
# floor with the widened matcher, and (b) SEED [hooks.state] so the floor is live on
# first run. The trusted_hash format is internal/opaque, so we never GUESS it: we ask
# codex itself for the value it computes (`codex app-server` -> hooks/list ->
# currentHash), which is deterministic and stable. Then we SELF-VERIFY: a deny probe
# fires under `codex exec` with NO bypass; if it doesn't, a wrong-hash drift has us
# failing OPEN, so we LOUDLY warn, strip the seeds, and fall back to documenting the
# bypass flag — never leaving the operator believing the floor is live when it isn't.
HOOKS_JSON="$DEST/hooks.json"
PRE_MATCHER='^(Read|Edit|Write|Bash|apply_patch)$'   # apply_patch is the Codex write tool
SEED_BEGIN='# >>> orchestrate hook-trust (managed; do not edit by hand) >>>'
SEED_END='#   <<< orchestrate hook-trust (managed) <<<'

# The PreToolUse floor, in wire order (must match the printed config-block order below).
# Each entry: <script-basename>.
PRE_HOOKS="deny-heldout-read.sh keep-on-branch.sh guard-shared-checkout.sh guard-done.sh gate-prod-apply.sh write-scope.sh run-scope.sh"

# Emit the managed hooks.json (CC-shaped — the shape codex reads from $CODEX_HOME/hooks.json).
# $1: extra PreToolUse matcher-group lines (used to append the self-verify probe group).
write_hooks_json() { # [<extra_group_json>]
  local extra="${1:-}" pre_hooks_json="" h
  for h in $PRE_HOOKS; do
    pre_hooks_json="${pre_hooks_json:+$pre_hooks_json, }{ \"type\": \"command\", \"command\": \"$HOOKS/$h\" }"
  done
  {
    printf '{ "hooks": {\n'
    printf '  "PreToolUse": [\n'
    printf '    { "matcher": "%s", "hooks": [ %s ] }%s\n' "$PRE_MATCHER" "$pre_hooks_json" "${extra:+,}"
    [ -n "$extra" ] && printf '    %s\n' "$extra"
    printf '  ],\n'
    printf '  "SubagentStart": [ { "matcher": "implementer|actuator", "hooks": [ { "type": "command", "command": "%s/on-writer-dispatch.sh" } ] } ],\n' "$HOOKS"
    printf '  "PostCompact": [ { "hooks": [ { "type": "command", "command": "%s/on-compaction.sh" } ] } ]\n' "$HOOKS"
    printf '} }\n'
  } > "$HOOKS_JSON"
}

# Ensure [features] hooks = true lands in config.toml (idempotent; never clobbers).
ensure_hooks_feature() { # <config.toml>
  local cfg="$1"
  [ -f "$cfg" ] || : > "$cfg"
  if ! grep -qE '^\s*hooks\s*=\s*true' "$cfg" 2>/dev/null; then
    printf '\n[features]\nhooks = true\n' >> "$cfg"
  fi
}

# Ensure the router's shell may reach the network (ADR-0017). Persona confinement runs each
# persona as its OWN nested `codex exec --cd <lane>` (dispatch-persona.sh); a nested codex
# needs the network to reach the model, but the default workspace-write sandbox blocks shell
# egress, so without this the launcher cannot dispatch. This brings Codex to Claude Code's
# existing network-open posture; persona WRITES stay OS-confined by `--cd` regardless.
# Idempotent; never clobbers an operator's existing key.
ensure_network_access() { # <config.toml>
  local cfg="$1"
  [ -f "$cfg" ] || : > "$cfg"
  if ! grep -qE '^\s*network_access\s*=' "$cfg" 2>/dev/null; then
    printf '\n[sandbox_workspace_write]\nnetwork_access = true\n' >> "$cfg"
  fi
}

# Strip any prior managed seed block (idempotent re-install).
strip_seed_block() { # <config.toml>
  local cfg="$1"; [ -f "$cfg" ] || return 0
  awk -v b="$SEED_BEGIN" -v e="$SEED_END" '
    $0==b {drop=1; next} $0==e {drop=0; next} !drop {print}
  ' "$cfg" > "$cfg.tmp" && mv "$cfg.tmp" "$cfg"
}

# Ask codex for the key->currentHash of every wired hook (deterministic oracle).
# Echoes lines "<key>\t<sha256:...>". Empty output -> oracle unavailable.
hook_trust_oracle() { # <CODEX_HOME>
  local ch="$1"
  { printf '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"clientInfo":{"name":"orchestrate-install","version":"0"}}}\n'
    sleep 1
    printf '{"jsonrpc":"2.0","id":2,"method":"hooks/list","params":{}}\n'
    sleep 2
  } | CODEX_HOME="$ch" timeout 30 codex app-server 2>/dev/null | python3 -c '
import sys, json
for line in sys.stdin:
    line=line.strip()
    if not line: continue
    try: m=json.loads(line)
    except Exception: continue
    if m.get("id")==2 and isinstance(m.get("result"),dict):
        for inst in m["result"].get("data",[]):
            for h in inst.get("hooks",[]):
                k=h.get("key"); v=h.get("currentHash")
                if k and v: print(f"{k}\t{v}")
        break
' 2>/dev/null
}

# Write the managed [hooks.state] block from "<key>\t<hash>" lines on stdin.
write_seed_block() { # <config.toml>  (reads key\thash pairs on stdin)
  local cfg="$1" key hash any=0 tmp; tmp="$(mktemp)"
  printf '%s\n' "$SEED_BEGIN" >> "$tmp"
  printf '[hooks.state]\n' >> "$tmp"
  while IFS=$'\t' read -r key hash; do
    [ -n "$key" ] && [ -n "$hash" ] || continue
    any=1
    printf '[hooks.state."%s"]\ntrusted_hash = "%s"\nenabled = true\n' "$key" "$hash" >> "$tmp"
  done
  printf '%s\n' "$SEED_END" >> "$tmp"
  [ "$any" = 1 ] && cat "$tmp" >> "$cfg"
  rm -f "$tmp"
  return $((1-any))   # 0 if we wrote at least one entry
}

# SELF-VERIFY: with the floor seeded (no bypass), a deny probe must BLOCK. Returns 0 on
# proven-live, non-zero otherwise. Uses an isolated throwaway CODEX_HOME that MIRRORS the
# real seeding flow (same hooks.json + same oracle + same [hooks.state] mechanism) plus one
# extra deny hook — so a PASS proves the exact seeding recipe makes a wired hook fire, while
# never depending on the model running a real floor hook against real state.
selfverify_trust() { # echoes PASS|FAIL|SKIP
  command -v codex >/dev/null 2>&1 || { echo SKIP; return; }
  command -v python3 >/dev/null 2>&1 || { echo SKIP; return; }
  codex login status >/dev/null 2>&1 || [ -f "$HOME/.codex/auth.json" ] || { echo SKIP; return; }
  local sv ws deny oracle out
  sv="$(mktemp -d)"; ws="$(mktemp -d)"
  [ -f "$HOME/.codex/auth.json" ] && cp "$HOME/.codex/auth.json" "$sv/auth.json" 2>/dev/null
  ( cd "$ws" && git init -q ) 2>/dev/null
  deny="$sv/selfverify-deny.sh"
  printf '#!/usr/bin/env bash\necho "ORCH-SELFVERIFY-DENY" >&2\nexit 2\n' > "$deny"; chmod +x "$deny"
  # A single deny hook on Bash — the same hooks.json shape + same trust mechanism.
  printf '{ "hooks": { "PreToolUse": [ { "matcher": "^(Bash|Shell|apply_patch)$", "hooks": [ { "type": "command", "command": "%s" } ] } ] } }\n' "$deny" > "$sv/hooks.json"
  printf '[features]\nhooks = true\n' > "$sv/config.toml"
  oracle="$(hook_trust_oracle "$sv")"
  [ -n "$oracle" ] || { rm -rf "$sv" "$ws"; echo SKIP; return; }
  printf '%s\n' "$oracle" | write_seed_block "$sv/config.toml" >/dev/null || { rm -rf "$sv" "$ws"; echo SKIP; return; }
  out="$(printf 'Run the shell command: echo orch-probe. Report the result.' \
    | ( cd "$ws" && CODEX_HOME="$sv" timeout 180 codex exec -s workspace-write --skip-git-repo-check - ) 2>&1)"
  rm -rf "$sv" "$ws"
  if printf '%s' "$out" | grep -qi "ORCH-SELFVERIFY-DENY"; then echo PASS; else echo FAIL; fi
}

# Drive the seeding + self-verify, set SEED_STATUS for the printed summary.
SEED_STATUS=unknown
seed_hook_trust() {
  write_hooks_json
  ensure_hooks_feature "$CONFIG_TOML"
  strip_seed_block "$CONFIG_TOML"
  # Oracle unavailable (no codex/auth)? Leave docs-only; floor needs manual trust.
  if ! command -v codex >/dev/null 2>&1 \
     || ! command -v python3 >/dev/null 2>&1 \
     || { ! codex login status >/dev/null 2>&1 && [ ! -f "$HOME/.codex/auth.json" ]; }; then
    SEED_STATUS=docs-only
    return 0
  fi
  local oracle
  oracle="$(hook_trust_oracle "$DEST")"
  if [ -z "$oracle" ]; then SEED_STATUS=docs-only; return 0; fi
  if ! printf '%s\n' "$oracle" | write_seed_block "$CONFIG_TOML" >/dev/null; then
    SEED_STATUS=docs-only; return 0
  fi
  # Load-bearing safety gate: prove the seeding recipe actually makes a hook FIRE.
  local v; v="$(selfverify_trust)"
  case "$v" in
    PASS) SEED_STATUS=seeded ;;
    SKIP) SEED_STATUS=seeded-unverified ;;       # seeded, but couldn't run the live probe
    *)    strip_seed_block "$CONFIG_TOML"; SEED_STATUS=verify-failed ;;  # drift -> strip, fall back to docs
  esac
}

# config.toml codex actually reads (user scope -> $DEST; project scope -> $DEST too).
CONFIG_TOML="$DEST/config.toml"
ensure_network_access "$CONFIG_TOML"   # ADR-0017: let the router launch confined persona sessions
seed_hook_trust

cat <<EOF

Codex install complete ($SCOPE scope).
  subagents -> $AGENTS_DEST/{...}.toml
  skill     -> $SKILL_DEST/  (SKILL.md + references/ + runtime/; codex auto-discovers
               .agents/skills — invoke \$orchestrate or let the description trigger; ADR-0034)
  hooks     -> $HOOKS_JSON  (wired; matcher includes apply_patch)
  trust     -> $CONFIG_TOML  ([features] hooks=true + [hooks.state] seeds)
  dispatch  -> personas run via $RT_DEST/dispatch-persona.sh (codex exec --cd <lane>); NOT spawn_agent (ADR-0017)
  network   -> $CONFIG_TOML  ([sandbox_workspace_write] network_access=true) so the router can launch confined persona sessions; matches Claude Code's network-open posture, persona WRITES stay OS-confined

Hook wiring + trust were applied automatically (status: $SEED_STATUS). The
reference config below documents the SAME wiring the installer wrote to
$HOOKS_JSON (you do NOT need to paste it unless you prefer config-inline hooks):

  # Hooks must be turned ON as a feature, or every [[hooks.*]] table below is inert.
  [features]
  hooks = true
  # Web search is BUILT IN and ON by default in codex 0.142.1; nothing to wire.
  # Uncomment ONLY to override the default mode (live|indexed|cached|disabled):
  #   web_search = "live"   # top-level, or under a [profiles.<name>]; per-role web_search is ignored.

  # NOTE on event names: the config TABLE names are PascalCase here
  # ([[hooks.PreToolUse]], SubagentStart, PostCompact). The wire \`hook_event_name\`
  # codex emits to the hook is also PascalCase. (Codex 0.142.1 has no snake_case
  # config table for these — unlike some harnesses. SubagentStart / PostCompact /
  # PreCompact are REAL events in this build, not stale.)

  [[hooks.PreToolUse]]
  matcher = "^(Read|Edit|Write|Bash|apply_patch)\$"   # apply_patch is the Codex top-level write tool
  [[hooks.PreToolUse.hooks]]
  type = "command"
  command = "$HOOKS/deny-heldout-read.sh"
  [[hooks.PreToolUse.hooks]]
  type = "command"
  command = "$HOOKS/keep-on-branch.sh"
  [[hooks.PreToolUse.hooks]]
  type = "command"
  command = "$HOOKS/guard-shared-checkout.sh"   # universal git-safety floor: refuse history-discarding ops on the PRIMARY shared checkout
  [[hooks.PreToolUse.hooks]]
  type = "command"
  command = "$HOOKS/guard-done.sh"               # done-gate hard floor: no \`done\` event without a Verifier verdict on the board
  [[hooks.PreToolUse.hooks]]
  type = "command"
  command = "$HOOKS/gate-prod-apply.sh"          # pre-apply gate hard floor (PreToolUse blocks; SubagentStart does not)
  [[hooks.PreToolUse.hooks]]
  type = "command"
  command = "$HOOKS/write-scope.sh"              # planner spec/ADR + researcher findings_quarantine + verifier verdicts confinement (self-guards; Write|Edit; ADR-0014)
  [[hooks.PreToolUse.hooks]]
  type = "command"
  command = "$HOOKS/run-scope.sh"                # verifier tests-only: deny workspace/git-mutating Bash (self-guards)

  # Write-ahead for both writers (deterministic ledger + lease; the gate's ledger half lives inside it):
  [[hooks.SubagentStart]]
  matcher = "implementer|actuator"
  [[hooks.SubagentStart.hooks]]
  type = "command"
  command = "$HOOKS/on-writer-dispatch.sh"

  # Automatic compaction recovery (hands-off):
  [[hooks.PostCompact]]
  [[hooks.PostCompact.hooks]]
  type = "command"
  command = "$HOOKS/on-compaction.sh"

>>> HOOK TRUST (fail-OPEN risk — status: $SEED_STATUS) <<<
A wired Codex hook SILENTLY NO-OPS — fails OPEN — unless its sha256 is trusted in
[hooks.state] (or the run passes --dangerously-bypass-hook-trust). These hooks are the
fail-closed floor (held-out reads, branch guard, prod-apply gate, done-gate); a silent
no-op disarms them. This installer SEEDS [hooks.state] automatically, using the hash
codex itself computes (\`codex app-server\` -> hooks/list -> currentHash; never a guess),
then SELF-VERIFIES that a wired hook actually fires with NO bypass. Outcome:
$(case "$SEED_STATUS" in
seeded) printf '%s' \
"  SEEDED + SELF-VERIFIED. The floor is LIVE on first run — no manual step. A deny
  probe blocked under \`codex exec\` with no bypass, proving the seeded trust takes.";;
seeded-unverified) printf '%s' \
"  SEEDED, NOT self-verified (could not run the live probe this install — e.g. no
  network/auth for a \`codex exec\` round-trip). The seeds use the codex-computed hash,
  but confirm once: run codex in the TUI and ensure no 'Hooks need review' prompt
  appears, OR re-run this installer where a live probe can complete.";;
verify-failed) printf '%s' \
"  *** SEEDING DID NOT TAKE — FLOOR IS NOT LIVE. *** The self-verify deny probe did NOT
  fire under \`codex exec\` even after seeding (likely a codex version/format DRIFT in
  the [hooks.state] key or hash recipe). The seeds were STRIPPED to avoid a false sense
  of safety. Until fixed, make the floor fire MANUALLY:
    1. Interactive: run codex once in the TUI and APPROVE the hooks when prompted.
    2. Headless/CI: \`codex exec --dangerously-bypass-hook-trust [PROMPT]\` (vetted only).
  Please report the drift: the key format or currentHash recipe changed.";;
docs-only) printf '%s' \
"  NOT seeded (codex/auth/python3 unavailable at install time, so the hash oracle and
  self-verify could not run). The floor is NOT live until you establish trust:
    1. Interactive: run codex once in the TUI and APPROVE the hooks when prompted.
    2. Headless/CI: \`codex exec --dangerously-bypass-hook-trust [PROMPT]\` (vetted only).
  Re-run this installer with codex logged in to seed + self-verify automatically.";;
*) printf '%s' "  (unknown seeding status)";;
esac)

Actuator credential confinement is ADVISORY (ADR-0002): scope the actuator lane's
creds to its leased targets in your deployment; serialization (the lease) is the
only guaranteed layer — the skill cannot enforce "no creds for an unleased target".

No config file. Web is built in (web_search, on by default); set ORCHESTRATE_WEB_MCP
ONLY to wire a custom web/doc MCP as an escape hatch. Set HELDOUT_ROOT, then run
/orchestrate to start or resume. Compaction recovers automatically via PostCompact.
Codex spawns subagents only on explicit request; agents.max_depth defaults to 1.
Ledger: .agents/runs/orchestrate/board.jsonl.
EOF
